{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.catalog "katalog") }}
{{- if include "fybrik.isEnabled" (tuple .Values.katalogConnector.enabled $autoFlag) }}
{{- if .Values.katalogConnector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.katalogConnector.serviceAccount.name }}
  labels:
    app.kubernetes.io/component: katalog-connector
    {{- include "fybrik.labels" . | nindent 4 }}
  {{- with .Values.katalogConnector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
