apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: katalog-editor
rules:
- apiGroups:
  - katalog.fybrik.io
  resources:
  - assets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
