{{- if .Values.worker.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: blueprints-role
rules:
- apiGroups:
  - app.fybrik.io
  resources:
  - blueprints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.fybrik.io
  resources:
  - blueprints/status
  verbs:
  - get
  - patch
  - update
{{- end }}

