{{- if .Values.manager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fybrik-config
data:
  {{- if .Values.coordinator.enabled }}
  CONNECTION_TIMEOUT: {{ .Values.manager.connectionTimeout | default .Values.global.connectionTimeout | quote }}
  CATALOG_PROVIDER_NAME: {{ .Values.coordinator.catalog | quote }}
  CATALOG_CONNECTOR_URL: {{ .Values.coordinator.catalogConnectorURL | default (printf "%s-connector:80" .Values.coordinator.catalog) | quote }}
  MAIN_POLICY_MANAGER_NAME: {{ .Values.coordinator.policyManager | quote }}
  MAIN_POLICY_MANAGER_CONNECTOR_URL: {{ .Values.coordinator.policyManagerConnectorURL | default (printf "%s-connector:80" .Values.coordinator.policyManager) | quote }}
  USE_EXTENSIONPOLICY_MANAGER: "false" # deprecated
  VAULT_ADDRESS: {{ tpl .Values.coordinator.vault.address . | quote }}
  VAULT_MODULES_ROLE: "module" # temporary
  {{- end }}
{{- end }}
