{{- if include "fybrik.isEnabled" (tuple .Values.manager.enabled (or .Values.coordinator.enabled .Values.worker.enabled)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "fybrik.fullname" . }}-leader-election-rb
  labels:
    {{- include "fybrik.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fybrik.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.manager.serviceAccount.name | default "default" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
