{{- if include "fybrik.isEnabled" (tuple .Values.manager.enabled .Values.coordinator.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fybrik.fullname" . }}-connector-ingress
  labels:
    {{- include "fybrik.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      fybrik.io/componentType: connector
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
{{- end }}