{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.policyManager "opa") }}
{{- $opaConnectorEnabled := include "fybrik.isEnabled" (tuple .Values.opaConnector.enabled $autoFlag) }}
{{- if include "fybrik.isEnabled" (tuple .Values.opaServer.enabled $opaConnectorEnabled) }}
apiVersion: v1
kind: Service
metadata:
  name: "opa"
  labels:
    app.kubernetes.io/component: opa
    {{- include "fybrik.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opaServer.service.type }}
  ports:
    - port: {{ .Values.opaServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: opa
    {{- include "fybrik.selectorLabels" . | nindent 4 }}
{{- end }}
