apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fybrik-manager-cr
rules:
- apiGroups:
  - ''
  resources:
  - events
  - secrets
  - secrets/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - persistentvolumeclaims
  - persistentvolumeclaims/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - pods
  - pods/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - app.fybrik.io
  resources:
  - blueprints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.fybrik.io
  resources:
  - blueprints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.fybrik.io
  resources:
  - fybrikapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.fybrik.io
  resources:
  - fybrikapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.fybrik.io
  resources:
  - fybrikmodules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.fybrik.io
  resources:
  - fybrikstorageaccounts
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - app.fybrik.io
  resources:
  - plotters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.fybrik.io
  resources:
  - plotters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  - deployments/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - jobs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - com.ie.ibm.hpsys
  resources:
  - datasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - motion.fybrik.io
  resources:
  - batchtransfers
  - batchtransfers/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - motion.fybrik.io
  resources:
  - batchtransfers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - motion.fybrik.io
  resources:
  - streamtransfers
  - streamtransfers/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - motion.fybrik.io
  resources:
  - streamtransfers/status
  verbs:
  - get
  - patch
  - update
